# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-25 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WBC', models.IntegerField(default='0')),
                ('Platelets', models.IntegerField(default='0')),
                ('RBC', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='LiverAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Albumin', models.IntegerField(default='0')),
                ('SGPT', models.IntegerField(default='0')),
                ('SGOT', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='00000', max_length=1000)),
                ('national_id', models.IntegerField(default='0')),
                ('address', models.CharField(max_length=1000)),
                ('password', models.CharField(default='00000', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='liveranalysis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahleel.Patient'),
        ),
        migrations.AddField(
            model_name='bloodanalysis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahleel.Patient'),
        ),
    ]
